In [79]:
import numpy as np
dtype = [('customer_id','i4'),('account_balance','f8'),('credit_score','i4'),('transaction_count','i4'),('years_active','i4'),('banking_data','f8')]
# Creating a structured array with the specified dtype
# Assuming we have some sample data for demonstration
# In a real scenario, you would load this data from a file or database


In [80]:
# create data
data = np.array([(1,25000.25,700,150,5, 5000.00),
                 (2,15000.00,650,100,3, 3000.00),
                 (3,50000.75,800,200,10, 10000.00),
                 (4,30000.50,720,120,7, 7500.00),
                 (5,20000.00,680,80,2, 2500.00),
                 (6,45000.00,750,180,8, 9000.00),
               ], dtype = dtype)
print(data) 
# this tells the numpy to use the structure we created earlier 
# so numpy now understands that we have 6 fields in our data and each field has a specific data type.
# column 1 is customer_id which is INTEGER FORMAT(I4)
# column 2 is account_balance which is FLOAT FORMAT(F8)
# column 3 is credit_score which is INTEGER FORMAT(I4)
# column 4 is transaction_count which is INTEGER FORMAT(I4)
# column 5 is years_active which is INTEGER FORMAT(I4)
# column 6 is banking_data which is FLOAT FORMAT(F8)

[(1, 25000.25, 700, 150,  5,  5000.) (2, 15000.  , 650, 100,  3,  3000.)
 (3, 50000.75, 800, 200, 10, 10000.) (4, 30000.5 , 720, 120,  7,  7500.)
 (5, 20000.  , 680,  80,  2,  2500.) (6, 45000.  , 750, 180,  8,  9000.)]


In [81]:
print(data['customer_id'])
print(data['account_balance'])
print(data['credit_score'])
print(data['transaction_count'])
print(data['years_active'])

[1 2 3 4 5 6]
[25000.25 15000.   50000.75 30000.5  20000.   45000.  ]
[700 650 800 720 680 750]
[150 100 200 120  80 180]
[ 5  3 10  7  2  8]


In [82]:
# QUESTION-1 ARRAY CREATION AND MANIPULATION
# Q1.1: Create a 4x4 identity matrix using 
numpy = np.eye(4)
print(numpy)



[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [83]:
#  Create an array of 8 zeros
numpy = np.zeros(8)
print(numpy)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [84]:
#  Create an array of 6 ones 
numpy = np.ones(6)
print(numpy)

[1. 1. 1. 1. 1. 1.]


In [85]:
# Create an array with values from 0 to 15 using
numpy = np.arange(16)
print(numpy)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [86]:
# Create an array with 8 evenly spaced values from 0 to 100
numpy = np.linspace(0, 100, 8)
print(numpy)


[  0.          14.28571429  28.57142857  42.85714286  57.14285714
  71.42857143  85.71428571 100.        ]


In [87]:
# QUESTION-2 Array Attributes and Information
# Q-2.1  What is the shape of the banking_data array?
numpy = np.shape(data)
print(numpy)

(6,)


In [88]:
# What is the data type of the banking_data array?
numpy = np.array(data)
print(numpy)

[(1, 25000.25, 700, 150,  5,  5000.) (2, 15000.  , 650, 100,  3,  3000.)
 (3, 50000.75, 800, 200, 10, 10000.) (4, 30000.5 , 720, 120,  7,  7500.)
 (5, 20000.  , 680,  80,  2,  2500.) (6, 45000.  , 750, 180,  8,  9000.)]


In [89]:
numpy = data.dtype
print(numpy)

[('customer_id', '<i4'), ('account_balance', '<f8'), ('credit_score', '<i4'), ('transaction_count', '<i4'), ('years_active', '<i4'), ('banking_data', '<f8')]


In [90]:
# What is the size (total number of elements) of the banking_data array?
numpy = np.size(data)
print(numpy)

6


In [91]:
# What is the number of dimensions of the banking_data array?
numpy = np.ndim(data)
print(numpy)

1


In [92]:
# What is the memory size of the banking_data array in bytes?
numpy = data.nbytes
print(numpy)
# attribute error 

192


In [93]:
# Question 3: Indexing and Slicing
# Q3.1: Extract the first row of banking_data
row_1 = data[0]
print(row_1)

(1, 25000.25, 700, 150, 5, 5000.0)


In [94]:
# Q3.2: Extract the last row of banking_data
row_last = data[-1]
print(row_last)

(6, 45000.0, 750, 180, 8, 9000.0)


In [95]:
# Q3.3: Extract the Account_Balance column (column index 1)
account_balance_column = data['account_balance']
print(account_balance_column)

[25000.25 15000.   50000.75 30000.5  20000.   45000.  ]


In [96]:
# Q3.4: Extract the first 4 rows and first 3 columns
rows = data[:4]
print(rows)

[(1, 25000.25, 700, 150,  5,  5000.) (2, 15000.  , 650, 100,  3,  3000.)
 (3, 50000.75, 800, 200, 10, 10000.) (4, 30000.5 , 720, 120,  7,  7500.)]


In [97]:
# Q3.5: Extract rows 3 to 7 (inclusive)
rows = data[2:7]
print(rows)


[(3, 50000.75, 800, 200, 10, 10000.) (4, 30000.5 , 720, 120,  7,  7500.)
 (5, 20000.  , 680,  80,  2,  2500.) (6, 45000.  , 750, 180,  8,  9000.)]


In [98]:
# Question 4: Mathematical Operations
# Q4.1: Calculate the sum of all account balances
total_balance = account_balance_column.sum()
print(total_balance)

185001.5


In [99]:
#  Calculate the mean account balance
mean_balance = np.mean(data['account_balance'])
print(mean_balance)

30833.583333333332


In [100]:
# Q4.3: Calculate the standard deviation of account balances
standard_deviation = np.std(data['account_balance'])
print(standard_deviation)

12720.445051394845


In [101]:
# Q4.4: Calculate the variance of account balances
variance = np.var(data['account_balance'])
print(variance)

161809722.30555558


In [102]:
# Q4.5: Calculate the median account balance
median = np.median(data['account_balance'])
print(median)

27500.375


In [103]:
# Question 5: Statistical Functions
# Q5.1: Find the minimum and maximum account balances
minimum = np.min(data['account_balance'])
maximum = np.max(data['account_balance'])
print(minimum)
print(maximum)

15000.0
50000.75


In [104]:
# Q5.2: Find the minimum and maximum credit scores
minimum_credit = np.min(data['credit_score'])
maximum_credit = np.max(data['credit_score'])
print(minimum_credit)
print(maximum_credit)

650
800


In [105]:
# Q5.3: Calculate the percentile values for account balances (25th, 50th, 75th)
percentiles_values = np.percentile(data['account_balance'], [25, 50, 75])
print(percentiles_values)

[21250.0625 27500.375  41250.125 ]


In [106]:
# Q5.4: Calculate the correlation between account balance and credit score
correlation = np.corrcoef(data['account_balance'], data['credit_score'])
print(correlation)

[[1.         0.97637231]
 [0.97637231 1.        ]]


In [107]:
# Q5.5: Calculate the covariance between account balance and credit score
covariance = np.cov(data['account_balance'], data['credit_score'])
print(covariance)

[[1.94171667e+08 7.23345333e+05]
 [7.23345333e+05 2.82666667e+03]]


In [108]:
# Question 6: Array Reshaping and Manipulation
# Q6.1: Reshape the banking_data to 5 rows × 10 columns
normal_data =  np.array(data.tolist())  # Convert structured array to a regular 2D array
flat_data = normal_data.flatten()  # Flatten the array to 1D
flat_data = np.pad(flat_data, (0, 50 - flat_data.size), mode='constant')  # Pad with zeros to reach 50 elements
reshaped_data = flat_data.reshape(5, 10)
print(reshaped_data)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03 2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02]
 [3.000000e+00 3.000000e+03 3.000000e+00 5.000075e+04 8.000000e+02
  2.000000e+02 1.000000e+01 1.000000e+04 4.000000e+00 3.000050e+04]
 [7.200000e+02 1.200000e+02 7.000000e+00 7.500000e+03 5.000000e+00
  2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00 2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]
 [0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00
  0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00]]


In [109]:
# Q6.2: Flatten the banking_data to a 1D array
flat_data = data.flatten()
print(flat_data)

[(1, 25000.25, 700, 150,  5,  5000.) (2, 15000.  , 650, 100,  3,  3000.)
 (3, 50000.75, 800, 200, 10, 10000.) (4, 30000.5 , 720, 120,  7,  7500.)
 (5, 20000.  , 680,  80,  2,  2500.) (6, 45000.  , 750, 180,  8,  9000.)]


In [110]:
# Q6.3: Transpose the banking_data
transposed = data.transpose()
print(transposed)

[(1, 25000.25, 700, 150,  5,  5000.) (2, 15000.  , 650, 100,  3,  3000.)
 (3, 50000.75, 800, 200, 10, 10000.) (4, 30000.5 , 720, 120,  7,  7500.)
 (5, 20000.  , 680,  80,  2,  2500.) (6, 45000.  , 750, 180,  8,  9000.)]


In [111]:
# Q6.4: Split the banking_data into 2 equal parts vertically
part1,part2 = np.array_split(data, 2)
print("part 1:\n",part1)
print("part 2:\n",part2)

part 1:
 [(1, 25000.25, 700, 150,  5,  5000.) (2, 15000.  , 650, 100,  3,  3000.)
 (3, 50000.75, 800, 200, 10, 10000.)]
part 2:
 [(4, 30000.5, 720, 120, 7, 7500.) (5, 20000. , 680,  80, 2, 2500.)
 (6, 45000. , 750, 180, 8, 9000.)]


In [112]:
# Q6.5: Split the banking_data into 2 equal parts horizontally
data = np.array(data.tolist())  # Convert structured array to a regular 2D array
part1,part2 = np.hsplit(data, 2)
print("part 1:\n",part1)
print("part 2:\n",part2)

part 1:
 [[1.000000e+00 2.500025e+04 7.000000e+02]
 [2.000000e+00 1.500000e+04 6.500000e+02]
 [3.000000e+00 5.000075e+04 8.000000e+02]
 [4.000000e+00 3.000050e+04 7.200000e+02]
 [5.000000e+00 2.000000e+04 6.800000e+02]
 [6.000000e+00 4.500000e+04 7.500000e+02]]
part 2:
 [[1.5e+02 5.0e+00 5.0e+03]
 [1.0e+02 3.0e+00 3.0e+03]
 [2.0e+02 1.0e+01 1.0e+04]
 [1.2e+02 7.0e+00 7.5e+03]
 [8.0e+01 2.0e+00 2.5e+03]
 [1.8e+02 8.0e+00 9.0e+03]]


In [113]:
# Question 7: Logical Operations and Filtering
# Q7.1: Find customers with account balance greater than $100,000
# Filter using column index (1 = account_balance)
high_balance_customers = data[data[:, 1] > 100000]
print(high_balance_customers)
# no customers with account balance greater than $100,000 in the data provided


[]


In [114]:
# Q7.2: Find customers with credit score greater than 800
credit_customers = data[data[:, 2] > 800]
print(credit_customers)
# no customers with credit score greater than 800 in the data provided


[]


In [115]:
# Q7.3: Find customers with transaction count greater than 50 AND credit score less than 750
filtered_customers = data[(data[:, 3] > 50) & (data[:, 2] < 750)]
print(filtered_customers)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03]]


In [116]:
# Q8.4: Find the customer with the second highest account balance
sorted_indices = np.argsort(data[:, 1])
# sort based on account balance
second_highest_index = sorted_indices[-2]
# get the index of the second highest account balance
second_highest_customer = data[second_highest_index]
# get the customer data for the second highest account balance
print(second_highest_customer)

[6.0e+00 4.5e+04 7.5e+02 1.8e+02 8.0e+00 9.0e+03]


In [117]:
# Q8.5: Find the customer with the lowest transaction count
sorted_indices = np.argsort(data[:, 3])
lowest_transaction_customer = data[sorted_indices[0]]
print(lowest_transaction_customer)


[5.0e+00 2.0e+04 6.8e+02 8.0e+01 2.0e+00 2.5e+03]


In [118]:
# Question 9: Mathematical Functions
# Q9.1: Calculate the absolute values of all elements
absolute_values = np.abs(data)
print(absolute_values)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03]]


In [119]:
# Q9.2: Calculate the square root of all account balances
square_balances = np.sqrt(data[:,1])
print(square_balances)

[158.11467358 122.47448714 223.60847479 173.20652413 141.42135624
 212.13203436]


In [120]:
# Q9.3: Calculate the square of all credit scores
credit_scores = data[:,2]
squared_credit_scores = np.square(credit_scores)
print(squared_credit_scores)

[490000. 422500. 640000. 518400. 462400. 562500.]


In [121]:
# Q9.4: Calculate the exponential of all transaction counts
transaction_counts = data[:,3]
exponential_transaction_counts = np.exp(transaction_counts)
print(exponential_transaction_counts)


[1.39370958e+65 2.68811714e+43 7.22597377e+86 1.30418088e+52
 5.54062238e+34 1.48938420e+78]


In [122]:
# Q9.5: Calculate the natural logarithm of all account balances
log_balances = np.log(data[:,1])
print(log_balances)

[10.1266411   9.61580548 10.81979328 10.30896933  9.90348755 10.71441777]


In [123]:
# Question 10: Advanced Operations
# Q10.1: Calculate the cumulative sum of account balances
cumulative_balances = np.cumsum(data[:,1])
print(cumulative_balances)

[ 25000.25  40000.25  90001.   120001.5  140001.5  185001.5 ]


In [124]:
# Q10.2: Calculate the cumulative product of transaction counts
cumulative_product = np.cumprod(data[:,3])
print(cumulative_product)

[1.500e+02 1.500e+04 3.000e+06 3.600e+08 2.880e+10 5.184e+12]


In [125]:
# Q10.3: Calculate the difference between consecutive account balances
balance_differences = np.diff(data[:,1])
print(balance_differences)

[-10000.25  35000.75 -20000.25 -10000.5   25000.  ]


In [126]:
# Q10.4: Calculate the gradient of account balances
gradient_balances = np.gradient(data[:,1])
print(gradient_balances)

[-10000.25   12500.25    7500.25  -15000.375   7499.75   25000.   ]


In [127]:
# Question 11: Random Numbers and Simulation
# Q11.1: Generate 6 random integers between 1 and 1000
random_integers = np.random.randint(1, 1001, size=6)
print(random_integers)

[199 830 478 141 931 696]


In [128]:
# Q11.2: Generate 6 random floats between 0 and 1
random_floats = np.random.rand(6)
print(random_floats)

[0.44804531 0.95596073 0.52986745 0.95781184 0.25015115 0.17967765]


In [129]:
# Q11.3: Generate 6 random numbers from normal distribution (mean=700, std=100)
random_normal = np.random.normal(700, 100, size=6)
print(random_normal)

[609.39248092 646.69400493 690.01539203 753.17812049 853.34079557
 566.23909285]


In [130]:
# Q11.4: Shuffle the banking_data rows randomly
shuffled_data = np.random.permutation(data)
print(shuffled_data)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03]]


In [131]:
# Q11.5: Set random seed to 123 and generate 4 random numbers
np.random.seed(123)
random_numbers = np.random.rand(4)
print(random_numbers)

[0.69646919 0.28613933 0.22685145 0.55131477]


In [132]:
# Question 12: Linear Algebra Operations
# Q12.1: Calculate the dot product of account balance and credit score columns
dot_product = np.dot(data[:,1], data[:,2])
print(dot_product)

136201135.0


In [133]:
import numpy as np
banking_data = np.array([
    [15000.50, 720, 25],
    [8200.75, 680, 18]
])
cross_product = np.cross(banking_data[0], banking_data[1])
print(cross_product)

[-4.040000e+03 -6.499025e+04  4.295800e+06]


In [134]:
# Q12.3: Calculate the norm (magnitude) of the account balance column
norm = np.linalg.norm(data[:,1])
print(norm)

81701.39228235342


In [135]:
# Q12.4: Create a 3x3 matrix and calculate its determinant
matrix = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [1, 0, 5]])
determinant = np.linalg.det(matrix)
print(determinant)

9.999999999999998


In [136]:
# Q12.5: Calculate the inverse of the 3x3 matrix
inverse_matrix = np.linalg.inv(matrix)
print(inverse_matrix)

[[ 0.5 -1.   0.5]
 [ 0.4  0.2 -0.4]
 [-0.1  0.2  0.1]]


In [137]:
# Question 13: String Operations
# Q13.1: Convert all customer IDs to strings
customer = data[:,0].astype(str)
print(customer)

['1.0' '2.0' '3.0' '4.0' '5.0' '6.0']


In [138]:
print(type(data))
print(data.shape)

<class 'numpy.ndarray'>
(6, 6)


In [139]:
# Q13.2: Check if any customer ID contains '100'
customer_contains = np.char.find(customer, '100')>=0
print(customer_contains)

[False False False False False False]


In [140]:
# Q13.3: Convert all customer IDs to uppercase (if they were strings)
customer_upper = np.char.upper(customer)
print(customer_upper)

['1.0' '2.0' '3.0' '4.0' '5.0' '6.0']


In [141]:
# Q13.4: Count the length of each customer ID string
customer_length = np.char.str_len(customer)
print(customer_length)

[3 3 3 3 3 3]


In [142]:
# Q13.5: Replace '100' with 'CUST' in customer IDs
# Step 1: Convert customer IDs to strings
customer_ids_str = data[:, 0].astype(str)
# Step 2: Replace '100' with 'CUST'
updated_ids = np.char.replace(customer_ids_str, '100', 'CUST')
print(updated_ids)

['1.0' '2.0' '3.0' '4.0' '5.0' '6.0']


In [143]:
# Question 14: Date and Time Operations
# Q14.1: Convert years active to months
months_active = data[:, 4] * 12
print(months_active)

[ 60.  36. 120.  84.  24.  96.]


In [144]:
# Q14.2: Calculate the average years active
average_years_active = np.mean(data[:, 4])
print(average_years_active)

5.833333333333333


In [145]:
# Q14.3: Find customers who have been active for more than 5 years
customers_active_more_than_5_years = data[data[:, 4] > 5]
print(customers_active_more_than_5_years)

[[3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03]]


In [146]:
# Q14.4: Calculate the total time all customers have been active (in years)
total_years_active = np.sum(data[:, 4])
print(total_years_active)

35.0


In [147]:
import numpy as np 

In [148]:
# Q14.5: Find the customer with the shortest time active


shortest_active_customer = data[data["years_active"] == np.min(data["years_active"])]
print(shortest_active_customer)

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [ ]:
# Question 16: Array Concatenation and Stacking

In [ ]:
# Q16.1: Concatenate two arrays horizontally using np.hstack()
data_regular = np.array(data.tolist())


In [ ]:
con = np.hstack((data_regular, data_regular))
print(con)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03 1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02
  5.000000e+00 5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03 2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02
  3.000000e+00 3.000000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04 3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02
  1.000000e+01 1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03 4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02
  7.000000e+00 7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03 5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01
  2.000000e+00 2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03 6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02
  8.000000e+00 9.000000e+03]]


In [ ]:
# Q16.2: Concatenate two arrays vertically using np.vstack()
data_regular = np.array(data.tolist())
con = np.vstack((data_regular, data_regular))
print(con)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03]
 [1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03]]


In [ ]:
# Q16.3: Concatenate arrays along a specific axis using np.concatenate()

cot = np.concatenate((data_regular, data_regular), axis=0)
print(cot)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03]
 [1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03]]


In [ ]:
# Q16.4: Stack arrays depth-wise using np.dstack()

cot = np.dstack((data_regular,data_regular))
print(cot)

[[[1.000000e+00 1.000000e+00]
  [2.500025e+04 2.500025e+04]
  [7.000000e+02 7.000000e+02]
  [1.500000e+02 1.500000e+02]
  [5.000000e+00 5.000000e+00]
  [5.000000e+03 5.000000e+03]]

 [[2.000000e+00 2.000000e+00]
  [1.500000e+04 1.500000e+04]
  [6.500000e+02 6.500000e+02]
  [1.000000e+02 1.000000e+02]
  [3.000000e+00 3.000000e+00]
  [3.000000e+03 3.000000e+03]]

 [[3.000000e+00 3.000000e+00]
  [5.000075e+04 5.000075e+04]
  [8.000000e+02 8.000000e+02]
  [2.000000e+02 2.000000e+02]
  [1.000000e+01 1.000000e+01]
  [1.000000e+04 1.000000e+04]]

 [[4.000000e+00 4.000000e+00]
  [3.000050e+04 3.000050e+04]
  [7.200000e+02 7.200000e+02]
  [1.200000e+02 1.200000e+02]
  [7.000000e+00 7.000000e+00]
  [7.500000e+03 7.500000e+03]]

 [[5.000000e+00 5.000000e+00]
  [2.000000e+04 2.000000e+04]
  [6.800000e+02 6.800000e+02]
  [8.000000e+01 8.000000e+01]
  [2.000000e+00 2.000000e+00]
  [2.500000e+03 2.500000e+03]]

 [[6.000000e+00 6.000000e+00]
  [4.500000e+04 4.500000e+04]
  [7.500000e+02 7.500000e+02]


In [ ]:

# Q16.5: Create a column stack using np.column_stack()

cot = np.column_stack((data_regular,data_regular))
print(cot)

[[1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02 5.000000e+00
  5.000000e+03 1.000000e+00 2.500025e+04 7.000000e+02 1.500000e+02
  5.000000e+00 5.000000e+03]
 [2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02 3.000000e+00
  3.000000e+03 2.000000e+00 1.500000e+04 6.500000e+02 1.000000e+02
  3.000000e+00 3.000000e+03]
 [3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02 1.000000e+01
  1.000000e+04 3.000000e+00 5.000075e+04 8.000000e+02 2.000000e+02
  1.000000e+01 1.000000e+04]
 [4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02 7.000000e+00
  7.500000e+03 4.000000e+00 3.000050e+04 7.200000e+02 1.200000e+02
  7.000000e+00 7.500000e+03]
 [5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01 2.000000e+00
  2.500000e+03 5.000000e+00 2.000000e+04 6.800000e+02 8.000000e+01
  2.000000e+00 2.500000e+03]
 [6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02 8.000000e+00
  9.000000e+03 6.000000e+00 4.500000e+04 7.500000e+02 1.800000e+02
  8.000000e+00 9.000000e+03]]


In [ ]:
# Question 17: Array Splitting Operations

In [ ]:
# Q17.1: Split an array into 3 equal parts using np.split()

data=np.split(data1,3)
print(data)

[array([[1.000000e+00, 2.500025e+04, 7.000000e+02, 1.500000e+02,
        5.000000e+00, 5.000000e+03],
       [2.000000e+00, 1.500000e+04, 6.500000e+02, 1.000000e+02,
        3.000000e+00, 3.000000e+03]]), array([[3.000000e+00, 5.000075e+04, 8.000000e+02, 2.000000e+02,
        1.000000e+01, 1.000000e+04],
       [4.000000e+00, 3.000050e+04, 7.200000e+02, 1.200000e+02,
        7.000000e+00, 7.500000e+03]]), array([[5.0e+00, 2.0e+04, 6.8e+02, 8.0e+01, 2.0e+00, 2.5e+03],
       [6.0e+00, 4.5e+04, 7.5e+02, 1.8e+02, 8.0e+00, 9.0e+03]])]


In [ ]:
# Q17.2: Split an array at specific indices using np.split()
dot=np.split(data1,[3,6])
dot

[array([[1.000000e+00, 2.500025e+04, 7.000000e+02, 1.500000e+02,
         5.000000e+00, 5.000000e+03],
        [2.000000e+00, 1.500000e+04, 6.500000e+02, 1.000000e+02,
         3.000000e+00, 3.000000e+03],
        [3.000000e+00, 5.000075e+04, 8.000000e+02, 2.000000e+02,
         1.000000e+01, 1.000000e+04]]),
 array([[4.00000e+00, 3.00005e+04, 7.20000e+02, 1.20000e+02, 7.00000e+00,
         7.50000e+03],
        [5.00000e+00, 2.00000e+04, 6.80000e+02, 8.00000e+01, 2.00000e+00,
         2.50000e+03],
        [6.00000e+00, 4.50000e+04, 7.50000e+02, 1.80000e+02, 8.00000e+00,
         9.00000e+03]]),
 array([], shape=(0, 6), dtype=float64)]

In [ ]:

# Q17.3: Split an array horizontally using np.hsplit()
# data_regular = np.array(data.tolist())
# dot = np.hsplit(data_regular, 2)
# print(dot)
# attribute error


AttributeError: 'list' object has no attribute 'tolist'

In [ ]:
# Q17.4: Split an array vertically using np.vsplit()
split=np.vsplit(data1,2)
split

[array([[1.000000e+00, 2.500025e+04, 7.000000e+02, 1.500000e+02,
         5.000000e+00, 5.000000e+03],
        [2.000000e+00, 1.500000e+04, 6.500000e+02, 1.000000e+02,
         3.000000e+00, 3.000000e+03],
        [3.000000e+00, 5.000075e+04, 8.000000e+02, 2.000000e+02,
         1.000000e+01, 1.000000e+04]]),
 array([[4.00000e+00, 3.00005e+04, 7.20000e+02, 1.20000e+02, 7.00000e+00,
         7.50000e+03],
        [5.00000e+00, 2.00000e+04, 6.80000e+02, 8.00000e+01, 2.00000e+00,
         2.50000e+03],
        [6.00000e+00, 4.50000e+04, 7.50000e+02, 1.80000e+02, 8.00000e+00,
         9.00000e+03]])]

In [ ]:
# Q17.5: Split an array into equal chunks using np.array_split()
split=np.array_split(data1,2)
split

[array([[1.000000e+00, 2.500025e+04, 7.000000e+02, 1.500000e+02,
         5.000000e+00, 5.000000e+03],
        [2.000000e+00, 1.500000e+04, 6.500000e+02, 1.000000e+02,
         3.000000e+00, 3.000000e+03],
        [3.000000e+00, 5.000075e+04, 8.000000e+02, 2.000000e+02,
         1.000000e+01, 1.000000e+04]]),
 array([[4.00000e+00, 3.00005e+04, 7.20000e+02, 1.20000e+02, 7.00000e+00,
         7.50000e+03],
        [5.00000e+00, 2.00000e+04, 6.80000e+02, 8.00000e+01, 2.00000e+00,
         2.50000e+03],
        [6.00000e+00, 4.50000e+04, 7.50000e+02, 1.80000e+02, 8.00000e+00,
         9.00000e+03]])]

In [ ]:

# Question 18: Array Repetition and Tiling

In [ ]:

# Q18.1: Repeat each element of an array 3 times using np.repeat()

rep=np.repeat(data1,3)
rep

array([1.000000e+00, 1.000000e+00, 1.000000e+00, 2.500025e+04,
       2.500025e+04, 2.500025e+04, 7.000000e+02, 7.000000e+02,
       7.000000e+02, 1.500000e+02, 1.500000e+02, 1.500000e+02,
       5.000000e+00, 5.000000e+00, 5.000000e+00, 5.000000e+03,
       5.000000e+03, 5.000000e+03, 2.000000e+00, 2.000000e+00,
       2.000000e+00, 1.500000e+04, 1.500000e+04, 1.500000e+04,
       6.500000e+02, 6.500000e+02, 6.500000e+02, 1.000000e+02,
       1.000000e+02, 1.000000e+02, 3.000000e+00, 3.000000e+00,
       3.000000e+00, 3.000000e+03, 3.000000e+03, 3.000000e+03,
       3.000000e+00, 3.000000e+00, 3.000000e+00, 5.000075e+04,
       5.000075e+04, 5.000075e+04, 8.000000e+02, 8.000000e+02,
       8.000000e+02, 2.000000e+02, 2.000000e+02, 2.000000e+02,
       1.000000e+01, 1.000000e+01, 1.000000e+01, 1.000000e+04,
       1.000000e+04, 1.000000e+04, 4.000000e+00, 4.000000e+00,
       4.000000e+00, 3.000050e+04, 3.000050e+04, 3.000050e+04,
       7.200000e+02, 7.200000e+02, 7.200000e+02, 1.2000

In [ ]:

# Q18.2: Repeat an entire array 2 times using np.tile()

rep=np.tile(data1,2)
rep

array([[1.000000e+00, 2.500025e+04, 7.000000e+02, 1.500000e+02,
        5.000000e+00, 5.000000e+03, 1.000000e+00, 2.500025e+04,
        7.000000e+02, 1.500000e+02, 5.000000e+00, 5.000000e+03],
       [2.000000e+00, 1.500000e+04, 6.500000e+02, 1.000000e+02,
        3.000000e+00, 3.000000e+03, 2.000000e+00, 1.500000e+04,
        6.500000e+02, 1.000000e+02, 3.000000e+00, 3.000000e+03],
       [3.000000e+00, 5.000075e+04, 8.000000e+02, 2.000000e+02,
        1.000000e+01, 1.000000e+04, 3.000000e+00, 5.000075e+04,
        8.000000e+02, 2.000000e+02, 1.000000e+01, 1.000000e+04],
       [4.000000e+00, 3.000050e+04, 7.200000e+02, 1.200000e+02,
        7.000000e+00, 7.500000e+03, 4.000000e+00, 3.000050e+04,
        7.200000e+02, 1.200000e+02, 7.000000e+00, 7.500000e+03],
       [5.000000e+00, 2.000000e+04, 6.800000e+02, 8.000000e+01,
        2.000000e+00, 2.500000e+03, 5.000000e+00, 2.000000e+04,
        6.800000e+02, 8.000000e+01, 2.000000e+00, 2.500000e+03],
       [6.000000e+00, 4.500000e+04,

In [ ]:

# Q18.3: Repeat a 2D array using np.tile()

rep = np.tile(data1, (2,2))
rep

array([[1.000000e+00, 2.500025e+04, 7.000000e+02, 1.500000e+02,
        5.000000e+00, 5.000000e+03, 1.000000e+00, 2.500025e+04,
        7.000000e+02, 1.500000e+02, 5.000000e+00, 5.000000e+03],
       [2.000000e+00, 1.500000e+04, 6.500000e+02, 1.000000e+02,
        3.000000e+00, 3.000000e+03, 2.000000e+00, 1.500000e+04,
        6.500000e+02, 1.000000e+02, 3.000000e+00, 3.000000e+03],
       [3.000000e+00, 5.000075e+04, 8.000000e+02, 2.000000e+02,
        1.000000e+01, 1.000000e+04, 3.000000e+00, 5.000075e+04,
        8.000000e+02, 2.000000e+02, 1.000000e+01, 1.000000e+04],
       [4.000000e+00, 3.000050e+04, 7.200000e+02, 1.200000e+02,
        7.000000e+00, 7.500000e+03, 4.000000e+00, 3.000050e+04,
        7.200000e+02, 1.200000e+02, 7.000000e+00, 7.500000e+03],
       [5.000000e+00, 2.000000e+04, 6.800000e+02, 8.000000e+01,
        2.000000e+00, 2.500000e+03, 5.000000e+00, 2.000000e+04,
        6.800000e+02, 8.000000e+01, 2.000000e+00, 2.500000e+03],
       [6.000000e+00, 4.500000e+04,

In [ ]:
# Q18.4: Create a pattern using np.tile()

pat = np.tile([[4,0],[0,4]], (3,3))
pat

array([[4, 0, 4, 0, 4, 0],
       [0, 4, 0, 4, 0, 4],
       [4, 0, 4, 0, 4, 0],
       [0, 4, 0, 4, 0, 4],
       [4, 0, 4, 0, 4, 0],
       [0, 4, 0, 4, 0, 4]])

In [ ]:
# Q18.5: Repeat elements with different counts using np.repeat()

rep = np.repeat(data1, 2)
rep

array([1.000000e+00, 1.000000e+00, 2.500025e+04, 2.500025e+04,
       7.000000e+02, 7.000000e+02, 1.500000e+02, 1.500000e+02,
       5.000000e+00, 5.000000e+00, 5.000000e+03, 5.000000e+03,
       2.000000e+00, 2.000000e+00, 1.500000e+04, 1.500000e+04,
       6.500000e+02, 6.500000e+02, 1.000000e+02, 1.000000e+02,
       3.000000e+00, 3.000000e+00, 3.000000e+03, 3.000000e+03,
       3.000000e+00, 3.000000e+00, 5.000075e+04, 5.000075e+04,
       8.000000e+02, 8.000000e+02, 2.000000e+02, 2.000000e+02,
       1.000000e+01, 1.000000e+01, 1.000000e+04, 1.000000e+04,
       4.000000e+00, 4.000000e+00, 3.000050e+04, 3.000050e+04,
       7.200000e+02, 7.200000e+02, 1.200000e+02, 1.200000e+02,
       7.000000e+00, 7.000000e+00, 7.500000e+03, 7.500000e+03,
       5.000000e+00, 5.000000e+00, 2.000000e+04, 2.000000e+04,
       6.800000e+02, 6.800000e+02, 8.000000e+01, 8.000000e+01,
       2.000000e+00, 2.000000e+00, 2.500000e+03, 2.500000e+03,
       6.000000e+00, 6.000000e+00, 4.500000e+04, 4.5000

In [ ]:
# Question 19: Array Comparison and Logical Operations

In [ ]:

# Q19.1: Compare two arrays for equality using np.array_equal()

data=np.array_equal(data1,data1)
data

True

In [ ]:
# Q19.2: Check if arrays are close using np.allclose()

dot=np.allclose(data1,data1)
dot

True

In [ ]:

# Q19.3: Apply logical AND operation between arrays

In [ ]:

# Q19.4: Apply logical OR operation between arrays

In [ ]:

# Q19.5: Apply logical NOT operation to an array

In [ ]:

# Question 20: Array Set Operations

In [ ]:

# Q20.1: Find unique elements in an array using np.unique()

data=np.unique(data1)
data

array([1.000000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00,
       5.000000e+00, 6.000000e+00, 7.000000e+00, 8.000000e+00,
       1.000000e+01, 8.000000e+01, 1.000000e+02, 1.200000e+02,
       1.500000e+02, 1.800000e+02, 2.000000e+02, 6.500000e+02,
       6.800000e+02, 7.000000e+02, 7.200000e+02, 7.500000e+02,
       8.000000e+02, 2.500000e+03, 3.000000e+03, 5.000000e+03,
       7.500000e+03, 9.000000e+03, 1.000000e+04, 1.500000e+04,
       2.000000e+04, 2.500025e+04, 3.000050e+04, 4.500000e+04,
       5.000075e+04])

In [ ]:
# Q20.2: Find the intersection of two arrays using np.intersect1d()

data=np.intersect1d(data1,data1)
data

array([1.000000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00,
       5.000000e+00, 6.000000e+00, 7.000000e+00, 8.000000e+00,
       1.000000e+01, 8.000000e+01, 1.000000e+02, 1.200000e+02,
       1.500000e+02, 1.800000e+02, 2.000000e+02, 6.500000e+02,
       6.800000e+02, 7.000000e+02, 7.200000e+02, 7.500000e+02,
       8.000000e+02, 2.500000e+03, 3.000000e+03, 5.000000e+03,
       7.500000e+03, 9.000000e+03, 1.000000e+04, 1.500000e+04,
       2.000000e+04, 2.500025e+04, 3.000050e+04, 4.500000e+04,
       5.000075e+04])

In [ ]:
# Q20.3: Find the union of two arrays using np.union1d()
data=np.union1d(data1,data1)
data

array([1.000000e+00, 2.000000e+00, 3.000000e+00, 4.000000e+00,
       5.000000e+00, 6.000000e+00, 7.000000e+00, 8.000000e+00,
       1.000000e+01, 8.000000e+01, 1.000000e+02, 1.200000e+02,
       1.500000e+02, 1.800000e+02, 2.000000e+02, 6.500000e+02,
       6.800000e+02, 7.000000e+02, 7.200000e+02, 7.500000e+02,
       8.000000e+02, 2.500000e+03, 3.000000e+03, 5.000000e+03,
       7.500000e+03, 9.000000e+03, 1.000000e+04, 1.500000e+04,
       2.000000e+04, 2.500025e+04, 3.000050e+04, 4.500000e+04,
       5.000075e+04])

In [ ]:
# Q20.4: Find elements in first array but not in second using np.setdiff1d()
data=np.setdiff1d(data1,data1)
data

array([], dtype=float64)

In [ ]:

# Q20.5: Find the symmetric difference between two arrays using np.setxor1d()

data=np.setxor1d(data1,data1)
data

array([], dtype=float64)